version: "3.8"
services: 
  pubsub_emulator:
    container_name: pubsub_emulator
    image: messagebird/gcloud-pubsub-emulator:latest
    ports: 
      - 8681:8681
    environment: 
      - PUBSUB_PROJECT1=qt-local-emulator,topic.name:subscriber.name